services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: gymos_admin
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3333/api/v1
      # VITE_API_URL: http://3.108.140.201/api/v1
    volumes:
      - .:/app
      - /app/node_modules
